esphome:
  name: camera

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "12345678"
  encryption:
    key: "8SILlmVAKKaBwk84A52nVZDsokjldSkGV7O7zTG0Cu4="

ota:
  password: "12345678"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Cam Fallback Hotspot"
    password: "12345678"

#esp32_camera_web_server:
#  - port: 8080
#    mode: stream

captive_portal:
    
# Example configuration entry
esp32_camera:
  name: Camera
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  reset_pin: GPIO15
  resolution: 1024x768
  jpeg_quality: 10
  vertical_flip: False
  horizontal_mirror: False